apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiLQoNCV0JfQo9Cb0KzQotCQ0KJf0JjQl1/QqNCQ0JPQkF8xIn19fQ==
type: kubernetes.io/dockerconfigjson
